spring.application.name=manage-your-little-fish

# import .env file
spring.config.import=optional:file:.env

spring.datasource.url=jdbc:postgresql://localhost:5432/littlefish
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Put flyway configuration here
spring.flyway.enabled=true
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
